### ISSUE TITLE
Top Banner says there are updates, but there are none

### ISSUE THREAD

**Issue by professionaljones** [Nexus-Mods/web-issues#113]
Title says it all. Not sure if bug or just affects me personally.

<img width="1920" alt="screen shot 2017-10-02 at 1 59 12 pm" src="https://user-images.githubusercontent.com/3934211/31091722-e7b935ba-a779-11e7-9ec1-d503ba4d5a4b.png">

**Comment by verenion** [comment]
Assigned PT#151632561

**Comment by Thallassa** [comment]
I can confirm. This just happened to me this morning; yesterday I received no updates at all. 

Steps to replicate:

Logged onto nexus. Had 4 updates. Only 3 were new (not greyed out). Clicked on those three. It still said I had one update, even though all visible updates were greyed out.

**Comment by iamtiz** [comment]
This should now be fixed

**Comment by mrmason** [comment]
Looks like this is still occurring for some users - reported in #137 by @heavyoak

**Comment by iamtiz** [comment]
Is anyone still experiencing this issue?

**Comment by Thallassa** [comment]
It is no longer happening for me.

**Comment by professionaljones** [comment]
Nope, not seeing it.

**Comment by heavyoak** [comment]
its fixed for me as well.

**Comment by mrmason** [comment]
Thanks guys - closing.
