### ISSUE TITLE
Tracking no longer working for 2 days now

### ISSUE THREAD

**Issue by Dreifels** [Nexus-Mods/web-issues#1209]
Get no more notifiacaations of user postings in mods which I have tracked. This for 2 days now.
It looks like no more any user gives a comment.

**Comment by Pickysaurus** [comment]
Reported on the forums: https://forums.nexusmods.com/index.php?/topic/9140998-notifications-not-working-atm/

Also reported on Reddit (although this isn't an official support platform) https://www.reddit.com/r/nexusmods/comments/iyl5lb/no_new_notifications/?utm_medium=android_app&utm_source=share

We are currently investigating this issue.

**Comment by Pickysaurus** [comment]
We have implemented a fix for this, however, currently, older notifications are no longer available as a result. We'll be making an announcement with more details shortly.

**Comment by Dreifels** [comment]
what you ever have done, it is no fix. 1) still get no niotifiation of tracking systerm and 2) login issue still is unchaanged along with massive timeouts and 3) now new: big mismatch after login, see screenshots.
I'm pretty sure that these are diferent issues maybe caused by a higher general issue. That*s not only database limit of stored messages.
Steps of the screenshots:
a) after putin in pwassword I got nothing response, then timeout, had to do same again,  also nothing, F5, then I got sceeensot 1, loot the upper line, that's not correct
b) then I searched for a mod c) foun dit, but look the top of thw windows, such is for not logged in users, not for after login. c) wanted to dpwnload it and got screen sor being not loged in. d) clicked on Login and got "You are alreadylogged in" but got e)  page for user being not logged in, then f) I could download it after click on browser "back"
that's all totally mismatched. Nothing got fixed, it's more worse than before
![login](https://user-images.githubusercontent.com/40837496/94315796-86778580-ff83-11ea-9d8e-5ff2bb55d8ba.jpg)
![login1](https://user-images.githubusercontent.com/40837496/94315816-8d05fd00-ff83-11ea-9379-11719de32857.jpg)
![login4](https://user-images.githubusercontent.com/40837496/94315859-a149fa00-ff83-11ea-9834-124ebbfe5253.jpg)
![login5](https://user-images.githubusercontent.com/40837496/94315894-adce5280-ff83-11ea-9eae-3a7ac7df91d5.jpg)
![login6](https://user-images.githubusercontent.com/40837496/94315909-b6bf2400-ff83-11ea-9695-d6898f0748b2.jpg)
![login2](https://user-images.githubusercontent.com/40837496/94315926-be7ec880-ff83-11ea-9770-f81d51c53abb.jpg)

**Comment by Dreifels** [comment]
and again, more massive and constant repeating, can't login
![01](https://user-images.githubusercontent.com/40837496/94320921-7d3fe600-ff8e-11ea-8afd-adb204ac8318.jpg)
![02](https://user-images.githubusercontent.com/40837496/94320926-7fa24000-ff8e-11ea-9530-09d5a6b51676.jpg)
