### ISSUE TITLE
Refine results does not function correctly, every with tags excluded.

### ISSUE THREAD

**Issue by heavyoak** [Nexus-Mods/web-issues#138]
![fireshot capture 039 - skyrim nexus - mods and community_ - https___rd nexusmods com_skyrim_mods_](https://user-images.githubusercontent.com/6599392/31242590-22c3b450-a9cd-11e7-8e19-f24761688e55.png)

even with the body slide tags excluded, its still show bodyslide. after turning a lot of things off, now stuff is not showing at all.

![fireshot capture 040 - skyrim nexus - mods a_ - https___www nexusmods com_skyrim_mods_searchresults_](https://user-images.githubusercontent.com/6599392/31242717-831c6bee-a9cd-11e7-933f-b1315f05bd00.png)

same settings, but what a difference.

**Comment by mrmason** [comment]
Assigned `PT#151734758`

**Comment by mrmason** [comment]
We've pushed some fixes to the way this works - Can you take a look now and see if it's working correctly ? Your screenshots don't show the same search I don't think so it's hard for me to test.

**Comment by heavyoak** [comment]
that's just it, I did not search for anything. I simply clicked the mods tab and applied the same filters on both sites.

with that said, filtering is working better on the new, but bodyslide stuff still shows up with when its filtered out, and applying filters takes x3 times as long on the new site as it does on the old site.

**Comment by heavyoak** [comment]
Notice the filters and the search results: 

![fireshot capture 043 - skyrim nexus - mods a_ - https___www nexusmods com_skyrim_mods_searchresults_](https://user-images.githubusercontent.com/6599392/31624141-4a7f23ec-b267-11e7-878a-901e31f0d11e.png)

same filters, considerably different results: 

![fireshot capture 045 - skyrim nexus - mods and community_ - https___rd nexusmods com_skyrim_mods_](https://user-images.githubusercontent.com/6599392/31624319-ed5f1b76-b267-11e7-9fda-b44942ffda19.png)

both are just the mods page, no search. same filters, same sorting. old shows everything that its sposed to, new shows other things. 

it should be the same results on both sites with the same settings (which I have to apply fresh each time on the new, old saves the settings), with the results in the same order.

**Comment by mrmason** [comment]
Hmm, I can't replicate what you're seeing on RD with the filtering - If you're sorting by endorsements DESC with very few filters then you _should_ be seeing SkyUI as the first result - this is what I see

<img width="1419" alt="screenshot 2017-10-16 18 03 35" src="https://user-images.githubusercontent.com/93157/31625030-832eeb20-b29c-11e7-88e5-512fa6fc5e57.png">

It looks like you're missing the first ~14 or so mods from the list. 

If you go here - `https://rd.nexusmods.com/users/28794?tab=user+files` - do you see any mods being blocked ?

What global tags have you got blocked in your user area ? `https://rd.nexusmods.com/users/myaccount?tab=content+blocking`

**Comment by heavyoak** [comment]
![fireshot capture 046 - my nexus account at nexus mods an_ - https___rd nexusmods com_users_myaccount](https://user-images.githubusercontent.com/6599392/31636341-a8cd60ee-b28f-11e7-97bb-adf7797e3604.png)

I have 2 that are bugged/errored.

Skyui is somehow being blocked on the new site, but shows up on the old.

![fireshot capture 047 - nexus mods and community_ - https___rd nexusmods com_users_28794](https://user-images.githubusercontent.com/6599392/31636392-de3a945e-b28f-11e7-807d-41410d8a9a31.png)

I use skyui, and ive endorsed it, so I have no idea why its blocked. might be the errored tags.

**Comment by mrmason** [comment]
We're looking into the broken tags at the moment - Can you let me know how your search results are looking now ? We just fixed a bug related to #77 that was to do with mods being blocked based on suggested tags that had been rejected.

**Comment by heavyoak** [comment]
the results look the same, and I still cant remove the errored tags. ive checked, I only have 4 blocked, but it still shows the two error ones as before.

![fireshot capture 049 - my nexus account at nexus mods an_ - https___rd nexusmods com_users_myaccount](https://user-images.githubusercontent.com/6599392/31702458-cc48dcde-b39c-11e7-80a4-21652f3bbc6f.png)

**Comment by mrmason** [comment]
@heavyoak - I've sent you an e-mail with an invitation to our slack group so if you're available we can try and debug this in real time.

**Comment by heavyoak** [comment]
sorry for the late reply, i had to take extra shifts at work. ive joined slack and ill be around.
