### ISSUE TITLE
Download overlay shown on new page if you change 'sort by' dropdowns

### ISSUE THREAD

**Issue by Pathoschild** [Nexus-Mods/web-issues#1398]
## Your username/username(s) affected
Pathoschild (probably affects all users).

## Bug/error being reported:
When you change any 'sort by' dropdown on the Files tab, clicking 'manual download' opens a new page instead of the modal overlay.

## Steps to reproduce:
1. Go to [any mod's 'files' tab](https://www.nexusmods.com/stardewvalley/mods/2400/?tab=files).
2. Change any 'sort by' dropdown to a different value ([screenshot](https://user-images.githubusercontent.com/230581/128037634-b4184c34-639c-4a52-b03e-6f908a4254e2.png)).
3. Click 'manual download' on any mod file ([screenshot](https://user-images.githubusercontent.com/230581/128037802-6c68715a-6440-4cf9-a284-d50e85f0c8e5.png)).

## Expected result:
The download should be appear in an overlay on the same page:  
![](https://user-images.githubusercontent.com/230581/128037951-d3b177d6-f9b7-4834-ad16-4f581f49d4cd.png)

## Actual result:
The button links to a new page:  
![](https://user-images.githubusercontent.com/230581/128038178-35a0bdc6-2c6e-4ded-9265-44a83ae95c11.png)

**Comment by Pickysaurus** [comment]
This should now be resolved?

**Comment by Pathoschild** [comment]
@Pickysaurus This still happens with the same repro steps. The new page at least has the site UI now. Here's with updated screenshots.

**Scenario 1: opens in modal as expected.**
1. Go to [any mod's 'files' tab](https://www.nexusmods.com/stardewvalley/mods/2400/?tab=files).
2. Click "Manual download" on any file. It [correctly opens in an overlay modal](https://user-images.githubusercontent.com/230581/195970168-c321eb67-58f6-45f3-b7af-679c4c0c7c14.png).

**Scenario 2: opens in new page.**
1. Go to [any mod's 'files' tab](https://www.nexusmods.com/stardewvalley/mods/2400/?tab=files).
2. Change the 'sort by' to any other value.
3. Click "Manual download" on any file. You're [redirected to a new page with the download](https://user-images.githubusercontent.com/230581/195970251-d15b325a-3c92-4c5d-b628-50d14d92f9a7.png).

It seems changing the sort loses the click handlers, so the browser just follows the download link.
