### ISSUE TITLE
"Delete this mod" function does not work

### ISSUE THREAD

**Issue by Zur13** [Nexus-Mods/web-issues#289]
Bug/error being reported: "Delete this mod" function does not work
Steps to reproduce:
1. Go to manage my mods page using site menu MODS->Manage my mods
2. Click "Delete this mod" link on some mod card
3. Confirm mod delete in the dialog

Expected result: Mod removed
Actual result: Mod disappeared but after page reload it is there again

If it is important I've accidentally created the mod, it is unpablished, it has no files, images etc, only mod name, version, author, brief overview and description.

**Comment by mrmason** [comment]
This is probably a caching issue - has the mod now disappeared for you ? What happened when you tried to visit the mod page itself after it had been deleted ?

**Comment by Hilli1** [comment]
I deleted a mod on the new website. The mod is removed. But on the old webside the mod is still there.

**Comment by Zur13** [comment]
I've removed the mod yesterday for the first time and today for the second time. Both times this mod reappeared after page reload and I was able to access mod page. It is still there and this is the mods page
https://rd.nexusmods.com/witcher3/mods/2742

**Comment by mrmason** [comment]
Assigned `PT#152474205`

**Comment by iamtiz** [comment]
Fixed

**Comment by Zur13** [comment]
I'm still could not delete the same mod. 

P.S. I don't know about the bug life cycle in your team. I'm sorry if the fix was not deployed yet and I'm bothering you

**Comment by iamtiz** [comment]
We found some other issues, all of which should be fixed now

**Comment by Zur13** [comment]
Yes the mod remove works, but there is some caching issues I think. Because mod card still appeared after mod was removed and page was reloaded.
![nexuserror11](https://user-images.githubusercontent.com/33193255/32556228-8b04a0b6-c4a7-11e7-915d-b5109d2744b5.png)


![nexuserror11_1](https://user-images.githubusercontent.com/33193255/32556237-90898434-c4a7-11e7-8c23-99a9fb6c6021.png)

**Comment by mrmason** [comment]
Hmm, we've tested this our end it disappeared straight away. 

If you're able to replicate this again, can you note down each step so we can see if we're doing the exact same thing ? I'm going to close this for now.

**Comment by Zur13** [comment]
I've stepped into caching issue again while prepared the test setup see #340.
