### ISSUE TITLE
Reflected XSS due to Post Parameter in search function.

### ISSUE THREAD

**Issue by Alyssa-o-Herrera** [Nexus-Mods/web-issues#297]
Bug/error being reported: A cross site scripting issue due to failure to sanitation and lack of escaping special characters. 
Steps to reproduce: 
We can submit a post request to the website with the following information using a post replay plugin like hackbar.
https://rd.nexusmods.com/search/
Post: gsearch=< img src=x onerror=prompt(document.cookie) >&gsearchtype=mods
Tested in firefox and we can see a pop up with the contents of our cookies.
Expected result: Sanitation and lack of injection of Html+Js into the web-page.
Actual result: Html characters are allowed to be used along side with java script access to DOM.  T

**Comment by Rrrafau** [comment]
assigned #152470407

**Comment by mrmason** [comment]
Should be fixed

**Comment by Alyssa-o-Herrera** [comment]
Still reproducible. 
https://rd.nexusmods.com/search/
post:
gsearch=2%22--%3E%3C%2Fscript%3E%3Csvg%2Fonload%3D%27%3Bconfirm%28document.domain%29%3B%27%3E&gsearchtype=mods
