### ISSUE TITLE
Click on the new comment notification does not open the comment

### ISSUE THREAD

**Issue by Zur13** [Nexus-Mods/web-issues#309]
Bug/error being reported: Click on notification about new comment does not open the comment
Steps to reproduce: Click on notification about new comment on your file
Expected result: the posts page shown and scrolled to the new comment
Actual result: The posts page is shown but does not scrolled to the new post

Please also note that if the Posts tab is already opened then click on new comment notification on the new site reloads the page while on the old site same action in the same situation jumps to the comment without page reload.

This is what the new site shows after the click on the new comment notification
![nexuserror7_1](https://user-images.githubusercontent.com/33193255/32346782-1e5e0f40-c017-11e7-86e4-ca2badf66d1c.png)

And this is what the old site shows after the click on the new same comment notification
![nexuserror7_2](https://user-images.githubusercontent.com/33193255/32346790-2d9d8512-c017-11e7-8b31-25356bcf0c01.png)

**Comment by Rrrafau** [comment]
Assigned #152541047

**Comment by mrmason** [comment]
this should be fixed

**Comment by BetaVirus** [comment]
still have the issue as of 11/28/17.   I click the new comments notification and it will take me to the mods main page. I click it a second time (marked as read) and it will take me to the comment. Only happens the first time to click a new notification all other times after it is marked read it load correctly to the comment.
