### ISSUE TITLE
Reordering thumbnails doesn't save properly

### ISSUE THREAD

**Issue by giftfish** [Nexus-Mods/web-issues#325]
**Bug/error being reported:**
Reordering thumbnails inside Manage > Media > Your Mod Images doesn't save properly.

**Steps to reproduce:**
Change the order of thumbnails. Save. Let the page reload on its own.

**Expected result:**
Thumbnails should adhere to the new order.

**Actual result:**
Thumbnails don't adhere to the new order. Nor do they appear as they did prior to changing their order. Results are not predictable.

New specified order-
![gallery_beforesave](https://user-images.githubusercontent.com/13645804/32416205-bb394192-c1fa-11e7-83fa-bc0185b3fd6d.JPG)

After page has been saved + reloaded-
![gallery_aftersave](https://user-images.githubusercontent.com/13645804/32416212-c7cdf74a-c1fa-11e7-89a0-94fb16f739d5.JPG)

---

I've found a few other bugs in the Edit Media interface. It could be that all or none are involved with this. In case, see also: #324, #322.

**Comment by verenion** [comment]
This might be because of the same issue as #322 - where loading the page via clicking on one of the header tabs would cause issues with future ajax calls. Loading the page directly seems to work. I have changed the loading system on that page, so, it should have resolved that issue.

**Comment by giftfish** [comment]
Doesn't look like it.

Just tested with the same mod page depicted above and the issue isn't resolved.

**Comment by giftfish** [comment]
@verenion -- I *just* saw the small message highlighted in orange about thumbs potentially needing a few hours to cycle through your CDN. I apologize for missing this earlier. 

Please hold off on doing any additional work for this. I'll get back to you in a few hours and let you know whether or not the changes have cycled through properly.

**Comment by giftfish** [comment]
Okay, @verenion , I can verify that no, the positioning changes are definitely still not working.

**Comment by ousnius** [comment]
@verenion: This is for the media tab (editing step), not the images tab.

**Comment by TheRealElianora** [comment]
I have this issue also when publishing new mods. I reordered the images in the Media tab, then moved around with the tabs, uploaded some more images, removed a couple, and the image order got all messed up. Sorry I don't know the exact steps to reproduce this issues.

**Comment by mrmason** [comment]
Assigned `PT#152848815`

**Comment by iamtiz** [comment]
This should be fixed now

**Comment by giftfish** [comment]
This is still not 100% fixed.

However, it is definitely improved. Most images I just reordered were exactly where they should be immediately after clicking "Save". Some changes are still not sticking, though, after multiple attempts. All problems seem to occur near the bottom of the thumbs. For the mod I'm testing with, that's around image 32 out of 43.

This is a strange bug. If there's any more information I can give you, please let me know. I know "sometimes this works and sometimes it doesn't" isn't much to go on.

**Comment by giftfish** [comment]
Follow up. There doesn't seem to be any lag; saving looks to be instant. If the thumb layout doesn't match what the mod author has specified at the time, then it's not going to later on.

**Comment by iamtiz** [comment]
Hi, did it happen just after having uploaded new images, or later on?

**Comment by ousnius** [comment]
It was definitely improved for me as well. Working more reliably. When I tried again yesterday, as giftfish said, the lower end didn't always stick in the right place.

Unfortunately I didn't check if this was after adding new images there or not. It sounds reasonable that it has something to do with new images, though.

**Comment by giftfish** [comment]
@iamtiz -- Uploading new images isn't required. For my report 4 days ago, I was simply swapping around what was already present. The fact that the order was only *partly* correct was visible immediately, and didn't take any lag time to show up. Nor did waiting a couple of hours change that.

**Comment by iamtiz** [comment]
We made some changes today. Can you check if the issue is solved for you? Thanks!

**Comment by giftfish** [comment]
@iamtiz -- Sorry to report there's no change. As reported previously, it does still seem confined to thumbs near the end.

**Comment by iamtiz** [comment]
@giftfish can you provide a link to one of your mods where this is still happening? Thanks!

**Comment by giftfish** [comment]
Sure.

[This is the one](https://rd.nexusmods.com/masseffect3/mods/411) I've been doing most of the testing with. I've tried a couple others, as well.

Hm. Here's a bit of a non-programming-level thought that may not be helpful for you. But, looking at the finished mod page, the problem might have something to do with how the thumbs are formatted across multiple pages. Most problems with order I'm seeing during testing are confined to the thumbs that end up on page two of the finished mod page.

**Comment by iamtiz** [comment]
Hi, there was an issue with that mod specifically, and that should be fixed now. Please let us know if it's working as intended now, and if you come across the same issue on other mods

**Comment by ousnius** [comment]
It happened for me on all these mod pages.
https://www.nexusmods.com/skyrimspecialedition/mods/13058
https://www.nexusmods.com/skyrimspecialedition/mods/13054
https://www.nexusmods.com/skyrimspecialedition/mods/13059
https://www.nexusmods.com/skyrimspecialedition/mods/13055

**Comment by iamtiz** [comment]
Closing for now, as we cannot replicate the issue. Let us know if you still have problems with image ordering though
