### ISSUE TITLE
Displaying blocked content

### ISSUE THREAD

**Issue by Kysakio** [Nexus-Mods/web-issues#412]
## Bug/error being reported:
The main page where it shows new mods displays mods with content that we are trying to block with your new website setup.

## Steps to reproduce:
Just go to the home page of a specific game's mods. For example:
https://www.nexusmods.com/skyrimspecialedition

## Expected result:
Should not display mods that we are intending to block.

## Actual result:
Displays mods as if we are not trying to block anything.

**Comment by Cryosaur** [comment]
It's strange: some mods tagged with proscribed content are blocked and some are not.

Example: in the New Today list right now are two Translation mods--Lore Weapon Expansion - Spanish, and Rigmor of Bruma - SMHK - Hungarian translation.  If I set the Translation tag as blocked, only the first mod is hidden (Spanish).  I'm not really sure why the Hungarian mod refuses to be hidden, even if I block the Hungarian tag, so here are a few differences between these two mods.
- The spanish mod disallows user tags but does have the correct tags for this discussion: Translation and Spanish.
- The hungarian mod allows user tags, and has Translation and Hungarian confirmed by author--locked at 99.
- Unsure if this is related but, for the hungarian mod, not all confirmed tags are actually visible on the mod page upon clicking View More in the tags region: Hungarian is present but Translation is not.

**Comment by Kysakio** [comment]
That's odd. I look forward to seeing if they go anywhere with this.

**Comment by iamtiz** [comment]
See also #416 

Internal task: #153403049

**Comment by iamtiz** [comment]
This should be fixed now

**Comment by Incarnax** [comment]
This is still not entirely working as intended.  With the Translation tag blocked in Content Blocking, some mods with that have the Translation tag are still visible.  After poking around for a few minutes, here are the things I noticed about the mods that are currently still slipping past the censor.

- User tags are allowed for these mods.
- Translation tag is confirmed by author (dark green, locked).
- No user tags are yet present.

For a few of these mods, I have voted on the tag for the specific language (which translation mod authors tend to leave out).  Strangely, after I did that, those mods were then successfully filtered.  It's like the blocker does not really believe mod authors' tags until a user votes on an additional tag.

My suspicion is that some code that makes Content Blocking effective was fixed, and is getting (re)executed when a user modifies tags, but is still missing/broken/not applied when an author creates or updates a mod.
