### ISSUE TITLE
The 'New' number by Updates tab does not show up at all

### ISSUE THREAD

**Issue by Eolhin** [Nexus-Mods/web-issues#471]
## Bug/error being reported:
The 'New' number by the Updates tab does not show up at all, despite there having been recent updates to things I am following, and those showing in the list if I check it.

## Steps to reproduce:
Follow things.
Receive updates on them listed on the Updates tab.
Never see a 'New' number appear on the Updates tab.

## Expected result:
To see that little number that warns me to check Updates (notifications), because there is new information there, when there is new information.

## Actual result:
No 'New' number appearing on the Updates tab.

Ever since this bug ticket:
#405 New count on Updates (Notifications) tab will not clear
Assigned #153557533
was listed as fixed, I have not had any 'New' number at all on my Updates tab show up.  I gave it a while in case it would resolve itself, but it did not.

Please tell me that "Fixed" does not mean that the malfunctioning feature was simply removed.  It was information available in the old layout, and it is important in order to keep up to date on Nexus notifications, as well as important updates on mods, and replies to posts.

**Comment by iamtiz** [comment]
assigned #154249035

**Comment by iamtiz** [comment]
This should be fixed now

**Comment by Eolhin** [comment]
I just checked, there was no 'New' number, but there were updates I had not previously seen, though I don't know just how long they had been there.  I can't be sure until something else updates, and I either get an 'New' number for it, or do not.

**Comment by Eolhin** [comment]
@iamtiz 
I have now several times gotten updates, and not had a 'New' number show up on the Updates tab, so the problem is definitely still happening.  (Chrome)  In fact, because of this I entirely missed the giveaway for the Steam gift card until it was already closed.  Do I need to submit a new ticket for this again??
