### ISSUE TITLE
Unable to login

### ISSUE THREAD

**Issue by xXBlackaiserXx** [Nexus-Mods/web-issues#713]
## Bug/error being reported:
When i try to log in, I see a message that says: captcha fail. I don't see any captcha. Like this:
![captura](https://user-images.githubusercontent.com/40325659/41502587-a720be60-71bd-11e8-81bc-dec3eb7bc9b9.JPG)
I tried with others explorers like Mozilla firefox, Google chrome and Opera, but I can only login with my mobile phone. I need to log in with my computer.
## Steps to reproduce:

 1. Go to Log in.
2. Write email address and password.
3. Click Sign.
4. Appears the error.
## Expected result:

Login to my account clicking the captcha.
## Actual result:

I can't login because there is no captcha

**Comment by kyle2912** [comment]
I am having the same issue, they really need to fix this. I've tried disabling all of my extensions and using firefox, explorer and microsoft edge and it still doesn't work.  Your not the only one, I hope its fixed soon

**Comment by saebel** [comment]
I can't log in via my mobile phone.  I just keep getting an incorrect user name/password error message.  I *know* I am using the correct user name/pw.  I even tried resetting it, but that didn't work either.

**Comment by xXBlackaiserXx** [comment]
I've already solved the problem, I just went to Mozilla Firefox, clicked up-right in the 3 bars, in options, then in privacy and security, in the history, and clean all the history, in range click All. Then, scroll down and in Cookies and data from the site, click in Clean Data, tick the two options and clean. Finally, doing this, i can see the captcha in all Internet Searchers.

**Comment by Vespii** [comment]
This is so frustrating, Ive cleared everything in multiple browsers and I cant log in because of this. I pay for this effin site too. Wasting my money.

**Comment by iamtiz** [comment]
Hi, we pushed some patches in the last few weeks. Do you stil have troubles logging in?

**Comment by theSnak3** [comment]
im also not getting the captcha one of the staff on the discord sent me a link to a modded login the have the captcha still not working 
![capture](https://user-images.githubusercontent.com/32428160/43998353-e2343e20-9dc1-11e8-8c74-308c86423312.PNG)
![help 1](https://user-images.githubusercontent.com/32428160/43998354-e664fcb4-9dc1-11e8-848c-31b39209ef01.PNG)

**Comment by theSnak3** [comment]
im have the same problem to im use edge
