### ISSUE TITLE
Search not displaying all mods

### ISSUE THREAD

**Issue by Nazenn** [Nexus-Mods/web-issues#77]
Possibly related to #43 but this is to do with the actual word part of the search not filters, so thought it may be more useful as a new post.

The RD site is not showing all possible results in its searches. Particularly noticable when searching for a specific filename, it will not show results that meet the exact same criteria over on the public version.

EG: https://www.dropbox.com/s/4cnaaua8x56p3e1/Screenshot%202017-09-18%2017.39.40.png?dl=0

There I searched PermaZones knowing there was two mods with that in the name, however RD showed neither while the main site showed both. If just searching for "zone" then it only showed PermaZones and NOT Static PermaZones. I've noticed this with quite a number of differant terms so its not an issue restricted purely to this search, this was just the easiest example, as other examples required hand checking each result between the two sites manually as it would miss some and not the others.

Another easy example: searching for dskal (looking for mods that have bloodskal in the title) shows 26 entries on the old search but only 20 on RD. This shows its also an issue with partial phrase searches as opposed to exact terms. 

This is also a confirmed bug when searching directly from the home page rather then via advanced search for a filename. (Eg when it comes up as search:dskal at the top rather then filename:dskal )

**Comment by Thallassa** [comment]
I think this is is an issue with the tag blocking bug mentioned with #22. I'm not sure though.

**Comment by Thallassa** [comment]
https://imgur.com/a/Ys8Pf Example of it happening - I'm told this mod is blocked, I am not blocking any of its tags, the tag that has been set to _ignore_ by the mod author is one that I am blocking. 

https://rd.nexusmods.com/skyrim/mods/78763

**Comment by mrmason** [comment]
This should be fixed - please can you let us know if you're seeing anything untoward.

**Comment by Thallassa** [comment]
I'm still seeing the message that "this mod contains content you have blocked" on the mod author page, but it does show up in search.

**Comment by Nazenn** [comment]
Its still happening and doesn't appear to be fixed at all unfortunately

I have no tags blocked, and when I search for PermaZone I still only get one result out of the two I should be getting. I do not have its author blocked or anything else that should be limiting it.

**Comment by mrmason** [comment]
We've pushed some fixes for the blocked-tags so most of this should hopefully be working.

There is one outstanding bug which is that on some pages ( like user's profiles ) - rejected tags are being treated like normal tags in terms of they're being incorrectly blocked. Assigned `PT#151518224`.

**Comment by Nazenn** [comment]
I don't currently have ANY tags blocked because of the previously mentioned issues with that and its still not showing for me, unless for some reason my tags have not been cleared on the server end at all but are showing clear on the user end. 
If I log out using the same firefox session it shows both mods if I search for PermaZones, but logged in it does not. Similarly clearing my cache/cookies etc has no bearing on it.
I got another user to run the same test with permazone and they can only see one as well, so at least we know its not just some weird issue on my end or account :)

**Comment by Thallassa** [comment]
Can confirm, https://www.nexusmods.com/skyrim/mods/searchresults/?src_order=2&src_sort=0&src_view=1&src_tab=1&src_name=permazones&src_language=0&page=1&pUp=1 shows two mods, but the exact same search on rd site https://rd.nexusmods.com/skyrim/search/ search keyword permazone, no filters, displays only one mod. morganmarz in discord also saw this behavior. I do have tags blocked but obviously it's the same on both sites (I haven't changed my blocking in a few weeks so it's had plenty of time to sync).

**Comment by mrmason** [comment]
Thanks guys - We're seeing that too - we are investigating - `PT#151520311`

**Comment by LordOfLA** [comment]
Thallassa directed me at this issue for the following reason:

When browsing a mod authors files list I'll have the overlay that some mods won't show in my search results on account of being blocked by my blocked tags setting.

However, upon comparing my list of blocked tags and the tags applied to the mod, the lists don't contain matching tags for the mods of compared. Thallassa tells me it's because tags the mod author rejected for the mod are in my block-list.

Example imgur gallery: https://imgur.com/a/DNEkJ

As to "clean browser" state, this is a fresh install of Windows 10 12699.15 and Firefox 57beta5 (which updated to beta 6 a short while before posting to this issue)

**Comment by mrmason** [comment]
We've pushed some fixes towards this and are testing it internally - please can you take a look on your end and see if it's working as you'd expect ?

**Comment by LordOfLA** [comment]
No, the example shown in my imgur album is still showing as shown in the album.

**Comment by Nazenn** [comment]
The tag stuff is a slightly differant issue LordOfLa

I can comfirm that the issue with the search results just flat out not appearing, irrelevent of the tag issue, appears to have been fixed.
Both Permazones mods are showing, all 25 mods now show with bloodska to show the bloodskal mods, and if you search something broader, like comb short for combat, then it shows all 241 mods accurately.
I would say it appears to be fixed. I'll let you know if I find any other jankiness with the search as I use it.

**Comment by LordOfLA** [comment]
Yeah discussing with Nazenn on the skyrimmods discord I should clarify I was only referring to the issue shown in my imgur album with it showing that content would be blocked based on the mod having rejected tags that match my blocked tags. I didn't test actual searching as I wasn't aware it was broken in the way Nazenn described in the post prior to this one.

**Comment by mrmason** [comment]
@LordOfLA - Can you give it another go now ? We think we've sorted it this time.

**Comment by LordOfLA** [comment]
Ok no longer seeing mods labelled as "will be filtered" based on blocked tags matching rejected tags. However, searching on crushboss on the Skyrim mini-site only yields two results not the expected 3 minimum.

**Comment by mrmason** [comment]
@LordOfLA - When I search Skyrim for `crushboss` I see 12 results.

Can you please provide us with more information on your search - including what blocked filters you've got - and which mod is being blocked when it shouldn't be - so we can investigate further?

**Comment by LordOfLA** [comment]
The blocked filters are in this image https://i.imgur.com/BwkN7oM.png. All I do is head over to https://rd.nexusmods.com/skyrim and type crushboss into the search box and hit enter.

That provides this result: https://i.imgur.com/HhAoYqv.png

What I expect to see is the three not flagged as filtered: https://i.imgur.com/K9jKLNr.png

Those filtered mods are filtered by tags suggested by users though. If I could toggle a setting to only filter by author tags that would be appreciated.
