### ISSUE TITLE
Performance issues when scrolling

### ISSUE THREAD

**Issue by ousnius** [Nexus-Mods/web-issues#9]
Chrome 60, Windows 10 x64, 1440p

When scrolling in fullscreen on any page, there are performance issues in the browser. Some time ago I found out that it's due to the following style attribute on the site background:

```css
background-attachment: fixed;
```

The attribute makes the background follow the current view of the scrolled site, instead of it staying at the top. This causes lags in my (hardware-accelerated) Chrome, but not in Internet Explorer or Edge.

The image size of the background doesn't matter, only the size after it's been scaled up to fit the screen.
As a rough estimate, without the fixed attribute, the site feels about twice as fast for me when scrolling.

Googling the issue, there are some workarounds (may have side effects).
```css
-webkit-transform:translatez(0);
```
This one didn't help on my system and broke the "Report bug" navbar.

Also, "it is actually a known bug since 2011, the background-attachment:fixed rule causes the browser to repaint the background on every scroll, which is an issue on large screens and Retina displays."
https://bugs.chromium.org/p/chromium/issues/detail?id=90637

**Comment by ousnius** [comment]
If you open the console in Chrome and go to the menu -> More tools -> Rendering to enable "Paint Flashing", you can see proof of this issue.

With a fixed background, the entire background is redrawn every scroll, with it turned off, nothing is redrawn except for the "Report bug" button that is moving to the scroll position.

**Comment by ousnius** [comment]
Exactly the same issue applies to the old design as well, but the performance loss isn't as big there. Still noticable.

**Comment by mrmason** [comment]
Assigned `PT#150803639`

We've pushed some changes for this - can you let us know if has improved @ousnius ?

**Comment by ousnius** [comment]
The new
```css
position: fixed;
```
is working!

But you forgot to remove the old
```css
background-attachment: fixed;
```
from the CSS. After disabling the old and keeping the new attribute, there lag is gone and the background still fixed. Thanks. :)

**Comment by mrmason** [comment]
Oops - that should be removed now!

**Comment by ousnius** [comment]
Smooth as butter!
